version: '3.8'

services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - POSTGRES_DB=gestion_flotte
      - POSTGRES_PASSWORD=BrouEzechiel2102
      - POSTGRES_USER=Ezechiel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres

volumes:
  db_data:
