version: '3.8'

services:
  postgres:
    image: 'postgres:16-alpine' # Version légère et très performante
    restart: always
    environment:
      - POSTGRES_DB=gestion_flotte
      - POSTGRES_USER=Ezechiel
      - POSTGRES_PASSWORD=BrouEzechiel2102
    ports:
      - "5432:5432" # Port par défaut de PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres

volumes:
  db_data: