spring.application.name=gestionflotte
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_flotte
spring.datasource.username=Ezechiel
spring.datasource.password=BrouEzechiel2102
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
application.security.jwt.secret-key=GWAEqcFPzPDY/8PBzO7hM6pG5iWhgw6+oGFyOX797pwpIO42daEHfdZqoXUX6xKqCPtsebGolD7iEnktHwZqdg